// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puqrbeiilxztbwcgskus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1cXJiZWlpbHh6dGJ3Y2dza3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTE0NzEsImV4cCI6MjA2NTUyNzQ3MX0.mM-7aKMRKnGoPyPk6JssfD75XdKAjquvoDqPh8A3diw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);